version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: minio-storage
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  pipeline:
    build: .
    container_name: worldbank-pipeline
    restart: "no"
    depends_on:
      - minio
    environment:
      S3_ENDPOINT: "http://minio:9000"
      S3_ACCESS_KEY: "minioadmin"
      S3_SECRET_KEY: "minioadmin"
      S3_REGION: "us-east-1"
      S3_BUCKET: "api-data"
    volumes:
      - ./data:/app/data

volumes:
  minio_data: